Реализовал Builder для классов PersonalInformation,TechnicalInformation
AlexAntufiev/EDATECH pull request #104
Opened 2021-05-04 18:49 UTC by shpikich

Для персональной информации сделал одним способом, для технической другим. У меня сомнения, какой из них правильнее

2021-05-04 19:36 UTC, AlexAntufiev requested changes

2021-05-04 19:36 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +        Profile profile = new Profile(technicalInformation, personalInformation);
а у профиля забыл билдер

2021-05-04 19:36 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/TechnicalInformation.java
> +        private final TechnicalInformation technicalInformation;
Самая плохая реализация
1. Все поля должны быть final
2. Здесь есть конструктор без аргументов по умолчанию, а нам нужен приватный
3. Билдер должен создавать объект только в методе билд, иначе он не билдер, а сеттер какой-то

2021-05-04 19:36 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/PersonalInformation.java
> +    private PersonalInformation(Builder builder) {
вариант рабочий и правильный. Можно было просто поменять паблике на приват и в методе билд вызывать приватный конструктор с кучей аргументов. Выбирай какой хочешь

2021-05-04 19:36 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +        TechnicalInformation technicalInformation = new TechnicalInformation.Builder()
можно было сделать статический метод в TechnicalInformation
`public static Builder builder(){
    return new Builder()
}`
и тогда сократить текст при вызове `TechnicalInformation.builder()`
Опять же на свое усмотрение

2021-05-06 17:48 UTC, shpikich commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +        TechnicalInformation technicalInformation = new TechnicalInformation.Builder()
Оставил, как было, потому что не совсем разобрался. Нужно будет уточнить

2021-05-07 22:16 UTC, AlexAntufiev approved these changes

2021-05-08 07:57 UTC, merged