Создал иерархию классов для профиля пользователя
AlexAntufiev/EDATECH pull request #98
Opened 2021-04-22 18:14 UTC by shpikich

2021-04-22 18:30 UTC, AlexAntufiev requested changes

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public Profile(TechnicalInformation a, PersonalInformation b) {
переменные нужно называть так, чтобы было понятно о чем она, то есть technicalInformation и personalInformation

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +                technicalInformation +
надо писать так: `"technicalInformation=" + technicalInformation` , то есть имя переменной и сама переменная
сгенерируй через Идею и посмотри как надо было сделать или посмотри как у тебя сделан TechnicalInformation

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final int id;
зачем паблик? id будем получать через геттер, ставь приват

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +class TechnicalInformation {
у этого класса должен быть модификатор public, ведь он должен быть отовсюду доступен. В джаве есть ограничение на 1 публичный класс в файле, поэтому давай этот класс вынесем в отдельный файл

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public String toString() {
некритично, но порядок примерно такой поля класса, конструктор, публичный методы, приватный методы

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +class PersonalInformation {
аналогичные замечания как и с TechnicalInformation

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final String DateOfBirth;
погугли объекты даты в java

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final String sex;
эта переменная может быть только 2 значений, поэтому нужен другой тип

2021-04-22 18:30 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final int id;
почитай про int, long, Integer, Long, BigInteger и подумай, что лучше тут будет

2021-04-27 17:32 UTC, shpikich commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final String sex;
Решил так:    
public enum Sex {
        Male, Female;
    }

    public Sex sex;

2021-04-27 17:33 UTC, shpikich commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final String sex;
public enum Sex {
        Male, Female;
    }
    public Sex sex;

2021-04-28 17:06 UTC, shpikich commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final String DateOfBirth;
public final LocalDate dateOfBirth;

2021-04-28 17:06 UTC, shpikich commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final String DateOfBirth;
public final LocalDate dateOfBirth;

2021-04-28 17:07 UTC, shpikich commented on src/main/java/ru/eda/tech/authorization/process/Profile.java
> +    public final int id;
private final long id;

2021-04-28 17:26 UTC, AlexAntufiev requested changes

2021-04-28 17:26 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/PersonalInformation.java
> +    public enum Sex {
давай тоже в отдельный файл

2021-04-28 17:26 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/PersonalInformation.java
> +    public final String name;
все поля приватные должны быть, чтобы другие не получили к ним доступ, а кто хочет, то использует геттер

2021-04-29 08:35 UTC, AlexAntufiev commented on src/main/java/ru/eda/tech/authorization/process/PersonalInformation.java
> +    private final Gender gender;
а ты вкурил подход) чем точнее ты определяешь тип объекта и его название к той предметной области, к котором он относится, тем лучше и проще это понимать потом

2021-04-29 08:36 UTC, AlexAntufiev approved these changes, later dismissed

2021-04-29 16:32 UTC, AlexAntufiev approved these changes

2021-04-29 16:33 UTC, merged